name: catalogscanner
description: An application used to scan your ACNH catalog.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.6+13

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.5.0
  camera: ^0.11.0+1
  flutter_share: ^2.0.0
  system_theme: ^3.0.0
  shared_preferences: ^2.2.3
  external_app_launcher: ^4.0.0
  url_launcher: ^6.2.6
  package_info_plus: ^8.0.0
  in_app_review: ^2.0.9


dependency_overrides:
  camera_android:
    git:
      url: https://github.com/elmar001/plugins.git
      path: packages/camera/camera_android
      ref: 5172b44088a4082ff0899594614c5380457d341b

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/dataSetTranslations.json
    - assets/data/translationsAppKeyed.json
